apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster1-waves-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chand01-g/myargo-platform1.git
    targetRevision: main
    path: apps-waves
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
