apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cart-helm-envs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: stage
          - env: prod

  template:
    metadata:
      name: cart-helm-{{env}}
    spec:
      project: default
      source:
        repoURL: https://github.com/chand01-g/myargo-platform1.git
        targetRevision: main
        path: charts/cart
        helm:
          valueFiles:
            - values-{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: cart-{{env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
